# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local Unix socket connections
local   all             all                                     trust

# IPv4 connections
host    all             all             0.0.0.0/0               md5

# IPv6 connections
host    all             all             ::/0                    md5

# Replication connections
host    replication    replicator    all    md5